# facebook tokens credentials
ACCESS_TOKEN = "<YOUR_FACEBOOK_PAGE_ACCESSTOKEN>"
VERIFY_TOKEN = "<YOUR_FACEBOOK_VERIFY_TOKEN>"


#IBM tokens
API_KEY = "<YOUR_IBM_API_KEY>"
IBM_URL = "<IBM_WATSON_URL>"

#Goodreads api credentials
GOODREADS_API_KEY = "<YOUR_GOODREADS_API_KEY>"
GOODREADS_SECRET = "<YOUR_GOODREADS_CLIENT_SECRET>"